export interface MenuItem {
	id: string;
	name: string;
	category: string;
	priceCents: number;
	isNew?: boolean;
}

// Menu data sourced from Pedro's real menu (menu.json), grouped by Pedro's own
// categories, including current specials. Demo still doesn't call Pedro's live menu API.
export const MENU: MenuItem[] = [
	{
		id: "loaded-full-chicken-paella",
		name: "Loaded Full Chicken Paella",
		category: "Specials",
		priceCents: 15999,
	},
	{
		id: "loaded-quarter-chicken-paella",
		name: "Loaded Quarter Chicken Paella",
		category: "Specials",
		priceCents: 5999,
	},
	{
		id: "loaded-chicken-strips-paella",
		name: "Loaded Chicken Strips Paella",
		category: "Specials",
		priceCents: 8999,
	},
	{
		id: "loaded-half-chicken-paella",
		name: "Loaded Half Chicken Paella",
		category: "Specials",
		priceCents: 8999,
	},
	{
		id: "1-4-chicken-chips-and-roll",
		name: "1/4 Chicken, Chips & Roll",
		category: "Favourites",
		priceCents: 4999,
	},
	{
		id: "1-2-chicken-meal",
		name: "1/2 Chicken Meal",
		category: "Favourites",
		priceCents: 8999,
	},
	{
		id: "full-chicken-paella",
		name: "Full Chicken Paella",
		category: "Favourites",
		priceCents: 14999,
	},
	{
		id: "viva-meal",
		name: "Viva Meal",
		category: "Favourites",
		priceCents: 15999,
	},
	{
		id: "full-meal",
		name: "Full Meal",
		category: "Favourites",
		priceCents: 19999,
	},
	{
		id: "double-up",
		name: "Double Up",
		category: "Favourites",
		priceCents: 6599,
	},
	{
		id: "strips-and-rice",
		name: "Strips & Rice",
		category: "Favourites",
		priceCents: 2999,
	},
	{
		id: "1-4-chicken",
		name: "1/4 Chicken",
		category: "Chicken Only",
		priceCents: 3299,
	},
	{
		id: "1-2-chicken",
		name: "1/2 Chicken",
		category: "Chicken Only",
		priceCents: 6499,
	},
	{
		id: "full-chicken",
		name: "Full Chicken",
		category: "Chicken Only",
		priceCents: 12499,
	},
	{
		id: "4-wings",
		name: "4 Wings",
		category: "Chicken Only",
		priceCents: 3999,
	},
	{
		id: "1-4-chicken-paella",
		name: "1/4 Chicken Paella",
		category: "Chicken Meals",
		priceCents: 4999,
	},
	{
		id: "1-2-chicken-paella",
		name: "1/2 Chicken Paella",
		category: "Chicken Meals",
		priceCents: 7999,
	},
	{
		id: "1-4-chicken-pap-and-chakalaka",
		name: "1/4 Chicken, Pap & Chakalaka",
		category: "Chicken Meals",
		priceCents: 4499,
	},
	{
		id: "1-4-chicken-and-chips",
		name: "1/4 Chicken & Chips",
		category: "Chicken Meals",
		priceCents: 4499,
	},
	{
		id: "4-flam-n-wings-and-chips",
		name: "4 Flam'n Wings & Chips",
		category: "Chicken Meals",
		priceCents: 4999,
	},
	{
		id: "4-wings-and-chips",
		name: "4 Wings & Chips",
		category: "Chicken Meals",
		priceCents: 4999,
	},
	{
		id: "1-4-chicken-chips-and-roll-2",
		name: "1/4 Chicken, Chips & Roll",
		category: "Chicken Meals",
		priceCents: 4999,
	},
	{
		id: "1-4-chicken-chips-and-garlic-roll",
		name: "1/4 Chicken, Chips & Garlic Roll",
		category: "Chicken Meals",
		priceCents: 5499,
	},
	{
		id: "1-4-chicken-meal",
		name: "1/4 Chicken Meal",
		category: "Chicken Meals",
		priceCents: 5999,
	},
	{
		id: "1-2-chicken-and-chips",
		name: "1/2 Chicken & Chips",
		category: "Chicken Meals",
		priceCents: 7999,
	},
	{
		id: "1-2-chicken-meal-2",
		name: "1/2 Chicken Meal",
		category: "Chicken Meals",
		priceCents: 8999,
	},
	{
		id: "1-2-viva-meal",
		name: "1/2 Viva Meal",
		category: "Chicken Meals",
		priceCents: 8499,
	},
	{
		id: "fiesta-meal",
		name: "Fiesta Meal",
		category: "Family Meals",
		priceCents: 17999,
		isNew: true,
	},
	{
		id: "chicken-strips-paella",
		name: "Chicken Strips Paella",
		category: "Family Meals",
		priceCents: 7999,
	},
	{
		id: "full-chicken-paella-2",
		name: "Full Chicken Paella",
		category: "Family Meals",
		priceCents: 14999,
	},
	{
		id: "full-chicken-and-4-rolls",
		name: "Full Chicken & 4 Rolls",
		category: "Family Meals",
		priceCents: 13999,
	},
	{
		id: "full-chicken-and-large-chips",
		name: "Full Chicken & Large Chips",
		category: "Family Meals",
		priceCents: 14999,
	},
	{
		id: "viva-meal-2",
		name: "Viva Meal",
		category: "Family Meals",
		priceCents: 15999,
	},
	{
		id: "viva-meal-4-garlic-rolls",
		name: "Viva Meal + 4 Garlic Rolls",
		category: "Family Meals",
		priceCents: 16999,
	},
	{
		id: "ola-meal",
		name: "Ola Meal",
		category: "Family Meals",
		priceCents: 16999,
	},
	{
		id: "full-meal-2",
		name: "Full Meal",
		category: "Family Meals",
		priceCents: 19999,
	},
	{
		id: "full-meal-4-garlic-rolls",
		name: "Full Meal + 4 Garlic Rolls",
		category: "Family Meals",
		priceCents: 20999,
	},
	{
		id: "mini-combo",
		name: "Mini Combo",
		category: "Family Meals",
		priceCents: 21999,
	},
	{
		id: "maxi-combo",
		name: "Maxi Combo",
		category: "Family Meals",
		priceCents: 25999,
	},
	{
		id: "mega-meal",
		name: "Mega Meal",
		category: "Family Meals",
		priceCents: 30999,
	},
	{
		id: "chicken-platter",
		name: "Chicken Platter",
		category: "Platters",
		priceCents: 50999,
	},
	{
		id: "kids-platter",
		name: "Kids Platter",
		category: "Platters",
		priceCents: 38999,
	},
	{
		id: "sprinkle-chicken-burger",
		name: "Sprinkle Chicken Burger",
		category: "Burger Meals",
		priceCents: 2999,
	},
	{
		id: "sprinkle-chicken-burger-and-chips",
		name: "Sprinkle Chicken Burger & Chips",
		category: "Burger Meals",
		priceCents: 3999,
	},
	{
		id: "sprinkle-chicken-burger-chips-and-300ml-buddy",
		name: "Sprinkle Chicken Burger, Chips & 300ml Buddy",
		category: "Burger Meals",
		priceCents: 4999,
	},
	{
		id: "chicken-burger",
		name: "Chicken Burger",
		category: "Burger Meals",
		priceCents: 3599,
	},
	{
		id: "chicken-burger-and-chips",
		name: "Chicken Burger & Chips",
		category: "Burger Meals",
		priceCents: 4599,
	},
	{
		id: "chicken-burger-chips-and-300ml-buddy",
		name: "Chicken Burger, Chips & 300ml Buddy",
		category: "Burger Meals",
		priceCents: 5499,
	},
	{
		id: "don-pedro-burger",
		name: "Don Pedro Burger",
		category: "Burger Meals",
		priceCents: 3599,
	},
	{
		id: "don-pedro-burger-and-chips",
		name: "Don Pedro Burger & Chips",
		category: "Burger Meals",
		priceCents: 4599,
	},
	{
		id: "don-pedro-burger-chips-and-300ml-buddy",
		name: "Don Pedro Burger, Chips & 300ml Buddy",
		category: "Burger Meals",
		priceCents: 5599,
	},
	{
		id: "cheese-burger",
		name: "Cheese Burger",
		category: "Burger Meals",
		priceCents: 3999,
	},
	{
		id: "cheese-burger-and-chips",
		name: "Cheese Burger and Chips",
		category: "Burger Meals",
		priceCents: 4999,
	},
	{
		id: "cheese-burger-chips-and-300ml-buddy",
		name: "Cheese Burger, Chips and 300ml Buddy",
		category: "Burger Meals",
		priceCents: 5999,
	},
	{
		id: "double-up-2",
		name: "Double Up",
		category: "Burger Meals",
		priceCents: 6599,
	},
	{
		id: "double-up-and-chips",
		name: "Double Up & Chips",
		category: "Burger Meals",
		priceCents: 7999,
	},
	{
		id: "double-up-chips-and-300ml-buddy",
		name: "Double Up, Chips & 300ml Buddy",
		category: "Burger Meals",
		priceCents: 8999,
	},
	{
		id: "slaw-wrap",
		name: "Slaw Wrap",
		category: "Wraps",
		priceCents: 3699,
	},
	{
		id: "slaw-wrap-and-chips",
		name: "Slaw Wrap & Chips",
		category: "Wraps",
		priceCents: 4699,
	},
	{
		id: "slaw-wrap-chips-and-300ml-buddy",
		name: "Slaw Wrap, Chips & 300ml Buddy",
		category: "Wraps",
		priceCents: 5699,
	},
	{
		id: "chicken-wrap",
		name: "Chicken Wrap",
		category: "Wraps",
		priceCents: 3999,
	},
	{
		id: "chicken-wrap-and-chips",
		name: "Chicken Wrap & Chips",
		category: "Wraps",
		priceCents: 4999,
	},
	{
		id: "chicken-wrap-chips-and-300ml-buddy",
		name: "Chicken Wrap, Chips & 300ml Buddy",
		category: "Wraps",
		priceCents: 5999,
	},
	{
		id: "cheesy-jalape-o-wrap",
		name: "Cheesy Jalape\u00f1o Wrap",
		category: "Wraps",
		priceCents: 4699,
	},
	{
		id: "cheesy-jalape-o-wrap-and-chips",
		name: "Cheesy Jalape\u00f1o Wrap & Chips",
		category: "Wraps",
		priceCents: 5699,
	},
	{
		id: "cheesy-jalape-o-wrap-chips-and-300ml-buddy",
		name: "Cheesy Jalape\u00f1o Wrap, Chips & 300ml Buddy",
		category: "Wraps",
		priceCents: 6699,
	},
	{
		id: "fully-loaded-wrap",
		name: "Fully Loaded Wrap",
		category: "Wraps",
		priceCents: 4999,
	},
	{
		id: "fully-loaded-wrap-and-chips",
		name: "Fully Loaded Wrap & Chips",
		category: "Wraps",
		priceCents: 5999,
	},
	{
		id: "fully-loaded-wrap-chips-and-300ml-buddy",
		name: "Fully Loaded Wrap, Chips & 300ml Buddy",
		category: "Wraps",
		priceCents: 6999,
	},
	{
		id: "cheesy-chicken-fries",
		name: "Cheesy Chicken Fries",
		category: "Single Meals",
		priceCents: 4999,
		isNew: true,
	},
	{
		id: "livers-and-roll",
		name: "Livers & Roll",
		category: "Single Meals",
		priceCents: 2999,
	},
	{
		id: "giblets-and-roll",
		name: "Giblets & Roll",
		category: "Single Meals",
		priceCents: 2999,
	},
	{
		id: "strips-and-rice-2",
		name: "Strips & Rice",
		category: "Single Meals",
		priceCents: 2999,
	},
	{
		id: "paella-bowl",
		name: "Paella Bowl",
		category: "Single Meals",
		priceCents: 2999,
		isNew: true,
	},
	{
		id: "chicken-salad",
		name: "Chicken Salad",
		category: "Single Meals",
		priceCents: 3999,
	},
	{
		id: "strips-and-chips",
		name: "Strips & Chips",
		category: "Single Meals",
		priceCents: 2999,
	},
	{
		id: "kids-chicken-nuggets-meal",
		name: "Kids Chicken Nuggets Meal",
		category: "Kids Meals",
		priceCents: 5499,
		isNew: true,
	},
	{
		id: "kids-chicken-bites-meal",
		name: "Kids Chicken Bites Meal",
		category: "Kids Meals",
		priceCents: 5499,
	},
	{
		id: "kids-burger-meal",
		name: "Kids Burger Meal",
		category: "Kids Meals",
		priceCents: 5499,
	},
	{
		id: "cheesy-fries",
		name: "Cheesy Fries",
		category: "Sides",
		priceCents: 3299,
		isNew: true,
	},
	{
		id: "onion-rings",
		name: "Onion Rings",
		category: "Sides",
		priceCents: 1399,
		isNew: true,
	},
	{
		id: "loaded-fries",
		name: "Loaded Fries",
		category: "Sides",
		priceCents: 3699,
	},
	{
		id: "garlic-roll",
		name: "Garlic Roll",
		category: "Sides",
		priceCents: 999,
	},
	{
		id: "cheesy-garlic-roll",
		name: "Cheesy Garlic Roll",
		category: "Sides",
		priceCents: 1399,
	},
	{
		id: "portuguese-roll",
		name: "Portuguese Roll",
		category: "Sides",
		priceCents: 599,
	},
	{
		id: "regular-chips",
		name: "Regular Chips",
		category: "Sides",
		priceCents: 1799,
	},
	{
		id: "regular-rice",
		name: "Regular Rice",
		category: "Sides",
		priceCents: 1799,
	},
	{
		id: "large-chips",
		name: "Large Chips",
		category: "Sides",
		priceCents: 2799,
	},
	{
		id: "large-rice",
		name: "Large Rice",
		category: "Sides",
		priceCents: 2799,
	},
	{
		id: "regular-wedges",
		name: "Regular Wedges",
		category: "Sides",
		priceCents: 1799,
	},
	{
		id: "large-wedges",
		name: "Large Wedges",
		category: "Sides",
		priceCents: 2799,
	},
	{
		id: "pap-and-chakalaka",
		name: "Pap & Chakalaka",
		category: "Sides",
		priceCents: 1999,
	},
	{
		id: "coleslaw-salad",
		name: "Coleslaw Salad",
		category: "Sides",
		priceCents: 1799,
	},
	{
		id: "garden-salad",
		name: "Garden Salad",
		category: "Sides",
		priceCents: 2799,
	},
	{
		id: "greek-salad",
		name: "Greek Salad",
		category: "Sides",
		priceCents: 3499,
	},
	{
		id: "dips",
		name: "Dips",
		category: "Sides",
		priceCents: 499,
	},
	{
		id: "5-chicken-nuggets-and-dip",
		name: "5 Chicken Nuggets & Dip",
		category: "Snacks",
		priceCents: 2999,
		isNew: true,
	},
	{
		id: "10-chicken-nuggets-and-dip",
		name: "10 Chicken Nuggets & Dip",
		category: "Snacks",
		priceCents: 4999,
		isNew: true,
	},
	{
		id: "12-chicken-bites-and-dip",
		name: "12 Chicken Bites & Dip",
		category: "Snacks",
		priceCents: 2999,
		isNew: true,
	},
	{
		id: "3-jalape-o-rissoles",
		name: "3 Jalape\u00f1o Rissoles",
		category: "Snacks",
		priceCents: 3499,
	},
];

export function findMenuItem(id: string): MenuItem | undefined {
	return MENU.find((item) => item.id === id);
}
